# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20160325_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='\u5b58\u6863\u65e5\u671f')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_essay', to='one.Essay')),
            ],
            options={
                'verbose_name': '\u5b58\u6863\u4fe1\u606f',
                'verbose_name_plural': '\u5b58\u6863\u4fe1\u606f\u5217\u8868',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
