# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20160325_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='eType',
        ),
        migrations.RemoveField(
            model_name='essaytype',
            name='baseType',
        ),
        migrations.DeleteModel(
            name='LevelMsg',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='EssayType',
        ),
    ]
